name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # This tells GitHub to look for your local machine
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: git -C $HOME/projects/WebNotifications pull origin main

      - name: SSH-restart-service
        run: |
          TMPFILE=$(mktemp)
          chmod 600 "$TMPFILE"
          echo "${{ secrets.SSH_PRIV_KEY }}" > "$TMPFILE"
          ssh -o IdentitiesOnly=yes -i "$TMPFILE" -o StrictHostKeyChecking=no 127.0.0.1
          rm "$TMPFILE"
